# Generated by Django 4.0 on 2021-12-31 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(db_column='number', error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, unique=True, verbose_name='Mission Number')),
                ('name', models.CharField(db_column='name', error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, max_length=120, unique=True, verbose_name='Mission Name')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_column='difficulty', default='easy', error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, max_length=50, verbose_name='Difficulty')),
                ('word', models.CharField(db_column='word', error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, max_length=500, verbose_name='Word')),
                ('point', models.IntegerField(db_column='point', error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, verbose_name='Mission Point')),
                ('time', models.IntegerField(db_column='time', error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, verbose_name='Mission Time')),
                ('create_at', models.DateTimeField(auto_now_add=True, db_column='create_at', error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, verbose_name='Created At')),
                ('update_at', models.DateTimeField(auto_now=True, db_column='update_at', error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, verbose_name='Update At')),
            ],
            options={
                'verbose_name_plural': 'Missions',
                'db_table': 'Mission',
            },
        ),
        migrations.CreateModel(
            name='CampaignRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win', models.IntegerField(db_column='win', default=0, error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, verbose_name='win')),
                ('lose', models.IntegerField(db_column='lose', default=0, error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, verbose_name='lose')),
                ('create_at', models.DateTimeField(auto_now_add=True, db_column='create_at', error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, verbose_name='Created At')),
                ('update_at', models.DateTimeField(auto_now=True, db_column='update_at', error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, verbose_name='Update At')),
                ('user', models.OneToOneField(db_column='user', error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Campaign Ranking',
                'db_table': 'CampaignRanking',
            },
        ),
    ]
