# Generated by Django 4.0 on 2021-12-31 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_draw', models.IntegerField(choices=[(10, 'Ten Sec'), (20, 'Twenty Sec'), (30, 'Thirty Sec')], db_column='time', default=30, error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, verbose_name='Time')),
                ('round', models.IntegerField(choices=[(2, 'Two'), (3, 'Three'), (4, 'Four')], db_column='round', default=2, error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, verbose_name='round')),
                ('number_of_users', models.IntegerField(choices=[(2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eight')], db_column='number_of_users', default=3, error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, verbose_name='number of user')),
                ('room_type', models.IntegerField(choices=[(1, 'public'), (2, 'Friend'), (3, 'Private')], db_column='room_type', default=1, error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, verbose_name='Room Type')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_column='difficulty', default='easy', error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, max_length=50, verbose_name='Difficulty')),
                ('room_code', models.CharField(db_column='room_code', default='941339e76202490385b2', error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, max_length=30, unique=True, verbose_name='Room Code')),
                ('create_at', models.DateTimeField(auto_now_add=True, db_column='create_at', error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, verbose_name='Created At')),
                ('update_at', models.DateTimeField(auto_now=True, db_column='update_at', error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, verbose_name='Update At')),
                ('creator', models.ForeignKey(db_column='creator', error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='Creator')),
            ],
            options={
                'verbose_name_plural': 'Rooms',
                'db_table': 'Room',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_column='word', error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, max_length=120, verbose_name='Word')),
                ('lenght', models.IntegerField(db_column='lenght', error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, verbose_name='lenght')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_column='difficulty', default='easy', error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, max_length=50, verbose_name='Difficulty')),
                ('create_at', models.DateTimeField(auto_now_add=True, db_column='create_at', error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, verbose_name='Created At')),
                ('update_at', models.DateTimeField(auto_now=True, db_column='update_at', error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, verbose_name='Update At')),
            ],
            options={
                'verbose_name_plural': 'Words',
                'db_table': 'Word',
            },
        ),
        migrations.CreateModel(
            name='RoomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, db_column='create_at', error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, verbose_name='Created At')),
                ('update_at', models.DateTimeField(auto_now=True, db_column='update_at', error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, verbose_name='Update At')),
                ('members', models.ManyToManyField(db_column='memebrs', error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, to=settings.AUTH_USER_MODEL, verbose_name='Members')),
                ('room', models.OneToOneField(db_column='room', error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, on_delete=django.db.models.deletion.CASCADE, related_name='roommember', to='online.room', verbose_name='Room')),
            ],
            options={
                'verbose_name_plural': 'RoomMember',
                'db_table': 'RoomMember',
            },
        ),
        migrations.CreateModel(
            name='OnlineRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win', models.IntegerField(db_column='win', default=0, error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, verbose_name='Win Count')),
                ('lose', models.IntegerField(db_column='lose', default=0, error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, verbose_name='Lose Count')),
                ('create_at', models.DateTimeField(auto_now_add=True, db_column='create_at', error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, verbose_name='Created At')),
                ('update_at', models.DateTimeField(auto_now=True, db_column='update_at', error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, verbose_name='Update At')),
                ('user', models.OneToOneField(db_column='user', error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'OnlineRanking',
                'db_table': 'OnlineRanking',
            },
        ),
    ]
