# Generated by Django 4.0 on 2021-12-31 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_code',
            field=models.CharField(db_column='room_code', default='05bcad719a474c938285', error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, max_length=30, unique=True, verbose_name='Room Code'),
        ),
        migrations.AlterField(
            model_name='roommember',
            name='room',
            field=models.OneToOneField(db_column='room', error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, on_delete=django.db.models.deletion.CASCADE, related_name='room_roommember', to='online.room', verbose_name='Room'),
        ),
    ]
