# Generated by Django 4.0.1 on 2022-01-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_code',
            field=models.CharField(db_column='room_code', default='e610924b63a249f79c43', error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, max_length=30, unique=True, verbose_name='Room Code'),
        ),
    ]
