# Generated by Django 4.0.1 on 2022-01-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0003_alter_room_room_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_code',
            field=models.CharField(db_column='room_code', default='58def6758eef4ec5ab7a', error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, max_length=30, unique=True, verbose_name='Room Code'),
        ),
    ]
