# Generated by Django 4.0 on 2021-12-31 13:57

from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(db_column='username', error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, max_length=200, unique=True, verbose_name='Username')),
                ('email', models.EmailField(db_column='email', error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, max_length=200, unique=True, verbose_name='Email')),
                ('friend_code', models.CharField(db_column='friend_code', default=user.models.User.random_friend_id, error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, max_length=20, unique=True, verbose_name='Friend Code')),
                ('image', models.URLField(db_column='image', default='https://none', error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, verbose_name='Image')),
                ('full_name', models.CharField(db_column='full_name', error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, max_length=200, verbose_name='Full Name')),
                ('role', models.IntegerField(choices=[(1, 'player'), (2, 'admin'), (3, 'owner')], db_column='role', default=1, error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, verbose_name='Role')),
                ('create_at', models.DateTimeField(auto_now_add=True, db_column='create_at', error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, verbose_name='Created At')),
                ('update_at', models.DateTimeField(auto_now=True, db_column='update_at', error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, verbose_name='Update At')),
                ('is_active', models.BooleanField(db_column='is_active', default=True, error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, verbose_name='is Active')),
                ('is_vip', models.BooleanField(db_column='is_vip', default=False, error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, verbose_name='is VIP')),
                ('is_donator', models.BooleanField(db_column='is_donator', default=False, error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, verbose_name='is Donator')),
            ],
            options={
                'verbose_name_plural': 'Users',
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='UserMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_number', models.IntegerField(db_column='mission_num', default=1, error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, verbose_name='Mision Number')),
                ('create_at', models.DateTimeField(auto_now_add=True, db_column='create_at', error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, verbose_name='Created At')),
                ('update_at', models.DateTimeField(auto_now=True, db_column='update_at', error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, verbose_name='Update At')),
                ('user', models.OneToOneField(db_column='user', error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'User Missions',
                'db_table': 'UserMission',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(db_column='total', default=0, error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, verbose_name='Total')),
                ('win', models.IntegerField(db_column='win', default=0, error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, verbose_name='Win')),
                ('lose', models.IntegerField(db_column='lose', default=0, error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, verbose_name='Lose')),
                ('level', models.IntegerField(db_column='level', default=0, error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, verbose_name='level')),
                ('point', models.IntegerField(db_column='point', default=0, error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, verbose_name='point')),
                ('create_at', models.DateTimeField(auto_now_add=True, db_column='create_at', error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, verbose_name='Created At')),
                ('update_at', models.DateTimeField(auto_now=True, db_column='update_at', error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, verbose_name='Update At')),
                ('user', models.OneToOneField(db_column='user', error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, on_delete=django.db.models.deletion.CASCADE, related_name='user_status_set', to='user.user')),
            ],
            options={
                'verbose_name_plural': 'Status',
                'db_table': 'Status',
            },
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, db_column='create_at', error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, verbose_name='Create At')),
                ('friend', models.ForeignKey(db_column='friend', error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, on_delete=django.db.models.deletion.CASCADE, related_name='friend_set', to='user.user')),
                ('user', models.ForeignKey(db_column='user', error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, on_delete=django.db.models.deletion.CASCADE, related_name='user_set', to='user.user')),
            ],
            options={
                'verbose_name_plural': 'Friends',
                'db_table': 'Friend',
            },
        ),
    ]
