# Generated by Django 4.0.1 on 2022-01-11 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='user',
            field=models.OneToOneField(db_column='user', error_messages={'blank': '...', 'invalid_choice': '...', 'max_lenght': '...', 'null': '...', 'required': '...', 'unique': '...'}, on_delete=django.db.models.deletion.CASCADE, related_name='user_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
